#!/usr/bin/env bash
# runme
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Update the userid
../utils/runtest

#Check if collection registration went through:
verify_registration dataObject-registration-response-header.tmp

SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`
DATAOBJECT_PATH=$(cat registered-dataobject-path.tmp)


#Get the registered dataObject by path
RESPONSE_HEADER=get-response-header.tmp
RESPONSE_MSG=get-response-message.json.tmp
get_item "dataObject/$DATAOBJECT_PATH" "$RESPONSE_HEADER" "$RESPONSE_MSG"


TRANSFER=$(get_json_value "$RESPONSE_MSG" transferPercentCompletion)
echo $TRANSFER
