#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-search/utils/search-functions

#Check if the dataObject exists before searching 

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

search_by_metadata dataObject input.json dice_user

HTTP_CODE=`get_http_code $RESPONSE_HEADER`

ATTRIBUTE="\"name\""
VALUE="dice test data file 2"


if [ ! "$HTTP_CODE" -eq "204" ]
then
    #Make sure the response does not include the object
    RESPONSE_GROUPS=`cat $RESPONSE_MSG | tr "{" "\n"`
    OBJECT_GROUPS=`echo "$RESPONSE_GROUPS" | grep "$ATTRIBUTE"`
    OBJECT_NAMES=`get_json_value "$OBJECT_GROUPS" value`
    
    
    OBJECT_FOUND="FALSE"
    for object in "$OBJECT_NAMES"; do
        if [[ $object == *"$VALUE"*  ]]
        then
            OBJECT_FOUND="TRUE"
            break
        fi
    done 
    
    if [ "$OBJECT_FOUND" == "TRUE" ] 
    then
        echo "ERROR: OBJECT \"$VALUE\" IS PART OF THE RESULTS."  1>&2
    fi
fi
