#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project 


#Clean previous results
./cleanme
$HPC_DM_TEST/utils/maketest
source $HPC_DM_TEST/utils/functions


USERID=$(get_username $HPC_DM_TEST/utils/config)

PROJECT_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-large-files"
echo "$PROJECT_PATH" > registered-project-path.tmp

PROJECT_DESCRIPTION="$HPC_DM_TEST/performance-tests/utils/register-project.json"

curl_register "$PROJECT_DESCRIPTION"  "$PROJECT_PATH"  collection
