#!/usr/bin/env bash
# upload-object 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Register an object with a specified size
# Usage: upload-object <file-size-in-MB> 
# Maximum file size is 100000 MBs ~ 100GB


source $HPC_DM_TEST/utils/functions
../utils/runtest

../utils/upload-object 10000
verify_registration dataObject-registration-response-header.tmp
