#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common script to make  to register a collection
# Usage: makeme


source $HPC_DM_TEST/utils/functions

#Register a parent project with a very unique attribute/value metadata
sleep 1
NAME=$(date +"%b-%d-%G-%H-%M-%S")
PROJECT_PATH="$(get_basefolder)/project-permission-$NAME"
PROJECT_DESCRIPTION=project-metadata.json

curl_register $PROJECT_DESCRIPTION  $PROJECT_PATH collection
echo "$PROJECT_PATH" > registered-project-path.tmp

cp $RESPONSE_HEADER project-response-header.tmp  
cp $RESPONSE_MSG project-response-message.json.tmp   2>/dev/null


#Give dice_user a "READ" permission for the project 
update_single_permission "collection/$PROJECT_PATH" dice_user READ

#Register a child folder 
FOLDER_PATH=$PROJECT_PATH/folder_path
FOLDER_DESC=$HPC_DM_TEST/utils/templates/register-folder-template.json
curl_register $FOLDER_DESC $FOLDER_PATH collection
echo "$FOLDER_PATH" > registered-folder-path.tmp

cp $RESPONSE_HEADER folder-response-header.tmp  
cp $RESPONSE_MSG folder-response-message.json.tmp   2>/dev/null
