#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

source $HPC_DM_TEST/utils/functions

#Clean previous results
./cleanme

#Call previous maketest
$HPC_DM_TEST/utils/maketest


