#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.

# Common script to run these tests 
# Usage: runtest [no arguments]

source $HPC_DM_TEST/utils/functions

