#!/usr/bin/env bash
# makeme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run common script
$HPC_DM_TEST/utils/runtest


RESPONSE_HEADER=user-registration-response-header.tmp
RESPONSE_MSG=user-registration-response-message.json.tmp

register_user_from_template
