#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-permission/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-permission/utils/runtest

#Verify the collection registration went through
verify_registration  collection-registration-response-header.tmp

#Update the input template with the new collection and user values  
COLLECTION_PATH=$(cat registered-project-path.tmp)
UPDATED_PATH=$(cat input.json | sed "s#dxcollectionpath#$COLLECTION_PATH#")
echo "$UPDATED_PATH" > input.json.tmp
    
#Submit the request to change permission
RESPONSE_HEADER=permission-response-header.tmp
RESPONSE_MSG=permission-response-message.json.tmp 
update_permission "input.json.tmp" "$RESPONSE_HEADER" "$RESPONSE_MSG"
 
HTTP_CODE=`get_http_code $RESPONSE_HEADER`

ERROR_TYPE=$(get_json_value $RESPONSE_MSG errorType)
ERROR_MESSAGE=$(get_json_value $RESPONSE_MSG message)

echo $HTTP_CODE 1>&2
echo $ERROR_TYPE 1>&2

EXPECTED_ERROR="Null or empty permission"
if [[ "$ERROR_MESSAGE" == *$EXPECTED_ERROR*  ]]
then
    echo $EXPECTED_ERROR 1>&2
fi

