#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


#$HPC_DM_TEST/utils/runtest
../utils/runtest

source $HPC_DM_TEST/utils/functions

collection_path=/$(get_basefolder)/dice_project1

sleep 1
suffix=`date +"%b-%d-%G-%H-%M-%S"`
bookmark_name=bookmark-$suffix
response_hdr=add-bookmark-response-header.tmp
response_msg=add-bookmark-response-message.json.tmp


add_bookmark $bookmark_name input.json "$response_hdr" "$response_msg"
get_http_code $response_hdr >&2
get_json_value $response_msg errorType >&2
get_json_value $response_msg message >&2

#Try to get the bookmark and make sure it is not there
response_hdr=get-bookmark-response-header.tmp
response_msg=get-bookmark-response-message.json.tmp
get_bookmark "$bookmark_name" "$response_hdr" "$response_msg"
get_http_code $response_hdr

