#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
#Register a project and a dataObject to be downloaded
#Optional input argument: dataObject-file. The registration will be done synchronously.

DATAOBJECT="$1"

source $HPC_DM_TEST/utils/functions
../../utils/maketest

#Register the project

USERID=$(get_username $HPC_DM_TEST/utils/config)
PROJECT_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-download"
register_collection_from_template "$PROJECT_PATH"

#Register the dataOjbect
NAME=`date +"%b-%d-%G-%H-%M-%S"`
DESTINATION_PATH=${PROJECT_PATH}/object-${NAME}.txt
echo "$DESTINATION_PATH" > registered-dataobject-path.tmp

curl_register register-dataobject.json.tmp  "$DESTINATION_PATH" dataObject "$DATAOBJECT"
