#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
#Register a dataObject synchronously


./cleanme 

echo "dxtest-string" >  dataObject-file.tmp
cp $HPC_DM_TEST/utils/templates/upload-input-template.json register-dataobject.json.tmp

../utils/maketest dataObject-file.tmp 

