#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
#Register a dataObject synchronously

source $HPC_DM_TEST/utils/functions
./cleanme 

update_uid $HPC_DM_TEST/utils/templates/register-dataobject-template.json register-dataobject.json.tmp
../utils/maketest 
