#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


source $HPC_DM_TEST/utils/functions
../../utils/maketest
 
#Clean previous results
./cleanme
update_uid ../utils/register-dataobject.json register-dataobject.json.tmp

#Register the project
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-download"
echo "$PROJECT_PATH" > registered-project-path.tmp
curl_register ../utils/register-project.json "$PROJECT_PATH" collection


#Register the dataOjbect
NAME=`date +"%b-%d-%G-%H-%M-%S"`
DESTINATION_PATH=${PROJECT_PATH}/object-${NAME}.txt
echo "$DESTINATION_PATH" > registered-dataobject-path.tmp
curl_register register-dataobject.json.tmp  "$DESTINATION_PATH" dataObject
