#!/usr/bin/env bash
# runtest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runtest 

#import common functions
source $HPC_DM_TEST/utils/functions

source $HPC_DM_TEST/utils/functions
if [ -e input-template.json ] 
then 
    update_uid input-template.json input.json
fi


