#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../utils/functions



RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat $HPC_DM_TEST/utils/server`


curl -H "Content-Type: application/json" -d @input.json -X POST ${SERVER}/hpc-server/dataObject/$OBJECT_PATH/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
check_connection $RESPONSE_HEADER

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
ERROR_TYPE=`get_json_value $RESPONSE_MSG errorType`

echo $HTTP_CODE 1>&2 
echo $ERROR_TYPE 1>&2
