#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-notifications/utils/runtest
verify_registration dataObject-registration-response-header.tmp 

async_sleep
async_sleep

#Make sure the dataObject is archived

OBJECT_PATH=$(cat registered-data-object-path.tmp)
OBJECT_GET_PATH=dataObject/$OBJECT_PATH

RESPONSE_HEADER=get-item-response-header.tmp 
RESPONSE_MSG=get-item-response-message.json.tmp

get_item "$OBJECT_GET_PATH"  "$RESPONSE_HEADER" "$RESPONSE_MSG"

ARCH_STATUS=$(get_json_attribute_value "$RESPONSE_MSG" "data_transfer_status")
if [ "$ARCH_STATUS" != "ARCHIVED" ]
then
    echo "Can not verify the archive status to be ARCHIVED. The notification can not be verified" 1>&2
    echo "data_transfer_status=$ARCH_STATUS" 1>&2
    exit
fi


#Get the last notifications
RESPONSE_HEADER=get-delivered-notifications-response-header.tmp 
RESPONSE_MSG=get-delivered-notifications-response-message.json.tmp

get_notification_receipts 

get_http_code $RESPONSE_HEADER

#Verify the message related to the uploaded object is present.

PRESENT=$(grep $OBJECT_PATH $RESPONSE_MSG)

if [ -z "$PRESENT" ]
then
    echo "ERROR: Can not find the notification related to $OBJECT_PATH" >&2
    exit 1
fi
