#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

sleep 1
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`

OBJECT_FILE=dataobject-${SUFFIX}.tmp
echo "data-$NAME" > $OBJECT_FILE

PROJECT_PATH=`cat registered-project-path.tmp`

#Register the original dataOject

register_dataobject_sync_from_template $PROJECT_PATH $OBJECT_FILE
verify_registration dataObject-registration-response-header.tmp


#calculate the md5sum
MDSUM=$(md5sum $OBJECT_FILE | awk '{ print $1 }')
echo $MDSUM > mdsum.tmp

#get the data object
DATAOBJECT_PATH=$(cat registered-data-object-path.tmp)

RESPONSE_HEADER=get-object-response-header.tmp
RESPONSE_MSG=get-object-response-message.json.tmp

get_item dataObject/$DATAOBJECT_PATH  $RESPONSE_HEADER $RESPONSE_MSG


#Check if the md5sum is part of the returned metadata
MDEXIST=$(grep  $MDSUM $RESPONSE_MSG)

if [ -z "$MDEXIST" ]
then
    echo "Failed to find the md5sum $MDEXIT in the datafile metadata $RESPONSE_MSG"
fi
