#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions
source ../../../utils/functions
NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username ../../../utils/config`
../../utils/registration-runtest collection ${USERID}/dice-unit-test/test-${NAME} INVALID_REQUEST_INPUT 
