#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Check if the collection and the dataObject registration functions called in makeme were successful.

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

query_by_metadata collection input.json dice_user

ATTRIBUTE="\"name\""

#Check that the collection is not returned 

VALUE="prasad project1 sub1"
RES=$(check_non_existance "$RESPONSE_HEADER" "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE")
