#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

SERVER=`cat $HPC_DM_TEST/utils/server`

#verify registration
verify_registration  collection1-registration-response-header.tmp
verify_registration  collection2-registration-response-header.tmp


PROJECT1_PATH=`cat registered-folder-path1.tmp`
PROJECT2_PATH=`cat registered-folder-path2.tmp`

NEW_USER_ID=$(cat new-user-id.tmp)


UPDATED_PROJECT1=$(cat input.csv | sed "s#collection1-path#$PROJECT1_PATH#")
UPDATED_PROJECT2=$(echo "$UPDATED_PROJECT1" | sed "s#collection2-path#$PROJECT2_PATH#")
UPDATED_ID=`echo "$UPDATED_PROJECT2" | sed "s#dxtestnewuserid#$NEW_USER_ID#"`
echo "$UPDATED_ID" > input.csv.tmp

#Register the collection in a batch mode 
ERROR_LOG="batch-error-log.tmp"
LOG="batch-log.tmp"
java  -Dhpc.client.properties=$HPC_DM_TEST/test-hpc-client/utils/hpc-client/hpc.properties -jar $HPC_DM_CLIENT --cmdfile ./batch_cmd.txt >$LOG 2>$ERROR_LOG
#echo "java  -Dhpc.client.properties=$HPC_DM_TEST/test-hpc-client/utils/hpc-client/hpc.properties -jar $HPC_DM_CLIENT --cmdfile ./batch_cmd.txt >$LOG 2>$ERROR_LOG"
#exit

#GET the SUCCESS  message
SUCCESS=$(grep "Batch process Successful" $ERROR_LOG)
if [[ -z "$SUCCESS" ]]
then
    echo "FAIL" 1>&2
else 
    echo "SUCCESS" 
fi

