#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


RESPONSE_HEADER=register-query-response-header.tmp
RESPONSE_MSG=register-query-response-message.json.tmp

HTTP_CODE=`get_http_code $RESPONSE_HEADER`

if [ ! "$HTTP_CODE" -eq "201" ]
then
    echo "Failed to register the query during makeme. " 
    exit
fi
    

REGISTERED_ID=$(cat registered-query-id.tmp)

RESPONSE_HEADER=get-query-response-header.tmp
RESPONSE_MSG=get-query-response-message.json.tmp
get_query "$REGISTERED_ID"

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE 

#Compare the returned query with the saved query
QUERY_MSG=$(cat query.json.tmp | sed "s/.*COLLECTION.*//" | tr -d " \t\n\r")
RETURNED_MSG=$(cat $RESPONSE_MSG | tr -d " \t\n\r")


#Makeme put the registered ID as part of the query.
PATTERN_EXISTS=$(grep "$REGISTERED_ID" $RESPONSE_MSG)

if [ -z "$PATTERN_EXISTS" ]
then
    echo "The returned query $RESPONSE_MSG does not match query.json.tmp" >&2
fi

#echo $RETURNED_MSG | sed "s#$QUERY_MSG#NONE#"
#echo $QUERY_MSG
#echo $RETURNED_MSG


