#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to clean the resutls of this test
# Usage: cleanme [no arguments]




# Script to build the executable for this test
# Usage: makeme [no arguments]

../util/maketest
