#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../utils/functions

#Run common script
../../utils/runtest

#Clean previous results
#./cleanme

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat ../../utils/server`


curl -H "Content-Type: application/json" -d @input.json -X PUT ${SERVER}/hpc-server/user  --config ../../utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
curl -H "Content-Type: application/json" -d @input.json -X PUT ${SERVER}/hpc-server/user  --config ../../utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 

check_connection $RESPONSE_HEADER

ERROR_TYPE=`get_json_value $RESPONSE_MSG errorType`
ERROR_REASON=`get_json_value $RESPONSE_MSG requestRejectReason`
#ERROR_TYPE=`grep errorType $RESPONSE_MSG | sed 's/.*errorType":"\([^"]*\)".*/\1/'`
#ERROR_CODE=`grep 'HTTP' $RESPONSE_HEADER  | grep '[02-9][0-9][0-9]' | sed 's/.*\([0-9][0-9][0-9]\).*/\1/'`
ERROR_CODE=`get_http_code $RESPONSE_HEADER`

echo $ERROR_CODE 1>&2
echo $ERROR_TYPE 1>&2
echo $ERROR_REASON 1>&2
