#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../../utils/functions
source ../../utils/search-functions


#Check if the collection and the dataObject registration functions called in makeme were successful.
check_registration
check_dataobject_registration


USERID=`get_username ../../../utils/config`

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat ../../../utils/server`

REGISTERED_OBJECT=`cat registered-dataobject-name.tmp`

get_item "/dataObject/${REGISTERED_OBJECT}" "$RESPONSE_HEADER" "$RESPONSE_MSG"
check_connection $RESPONSE_HEADER

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

