#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]


#Clean previous parsed policies file
../../utils/cleantest

# Script to build the executable for this test
# Usage: makeme [no arguments]
../../../utils/maketest

#Register a collection
source ../../../utils/functions
USERID=`get_username ../../../utils/config`
COLLECTION_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-add-dataobject"
echo "$COLLECTION_PATH" >> registered-project-path.tmp

register_collection_from_template "$COLLECTION_PATH"
#curl_register project-description.json "$COLLECTION_PATH" collection

verify_registration collection-registration-response-header.tmp
mv collection-registration-response-header.tmp original-collection-registration-response-header.tmp

#Register a dataOjbect
register_dataobject_async_from_template  "$COLLECTION_PATH"

