#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

OBJECT_PATH=`cat registered-dataobject-path.tmp`
#FILE_NAME=$(basename $OBJECT_PATH)

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat $HPC_DM_TEST/utils/server`

GLOBUS_STATUS="IN_PROGRESS"

get_item "/dataObject/${OBJECT_PATH}" "$RESPONSE_HEADER" "$RESPONSE_MSG"
check_connection $RESPONSE_HEADER

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

RESPONSE_GROUPS=`cat $RESPONSE_MSG | tr "{" "\n" | grep "data_globus_status" `
GLOBUS_STATUS=`get_json_value $RESPONSE_GROUPS value `
echo $GLOBUS_STATUS

#Do not check the file is the code is not 200
if [ $HTTP_CODE != 200 ] 
then
    exit
fi

