#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


#Clean previous results
./cleanme
$HPC_DM_TEST/test-permission/utils/maketest


source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-permission/utils/functions

register_new_project_and_user
register_group_from_template
NEW_USER_ID=$(cat new-user-id.tmp)
NEW_GROUP_ID=$(cat new-group-id.tmp)

add_user_to_group "$NEW_GROUP_ID"  "$NEW_USER_ID"

#Replace new-user-id with new-group-id to reuse the test utilities
mv new-user-id.tmp original-new-user-id.tmp
cp new-group-id.tmp new-user-id.tmp
