#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-notifications/utils/runtest


subscribe_to_template_notifications


RESPONSE_HEADER=subscribe-notifications-response-header.tmp
RESPONSE_MSG=subscribe-notifications-response-message.json.tmp


HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

#Parse the response header. 

#Divide the output by {
#SEPARATE_LINES=$(cat $RESPONSE_MSG | tr "{" "\n")
#GROUP_RESPONSE=$(echo "$SEPARATE_LINES" | grep "\"group\"")
#
#
##Make sure the group is added "result true"
#if ! [[ "$GROUP_RESPONSE" ==  *"\"result\":true"*  ]] 
#then
#    echo "ERROR: The group was not added correctly"
#    exit
