#!/usr/bin/env bash
# cleantest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to clean the resutls of this test
# Usage: cleantest [no arguments]

