#!/usr/bin/env bash
# functions
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common functions used by the unit tests

#Returns the possible notifications from the notifications template file
function get_possible_notifications {

    source $HPC_DM_TEST/utils/functions 
    SUBSCRIPTION_TEMPLATE=$HPC_DM_TEST/utils/templates/notifications_template.json
    NOTF_FILE=$(cat $SUBSCRIPTION_TEMPLATE)
    SEPARATE_LINES=$(echo $NOTF_FILE | tr "," "\n")
    NOTIFICATION_TYPES=$(get_json_value "$SEPARATE_LINES" "eventType")
    echo "$NOTIFICATION_TYPES"
}
