#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../../utils/functions
source ../../utils/search-functions

./cleanme


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat ../../../utils/server`

curl -G  -X GET $SERVER/hpc-server/dataObject/dxtest/dxtest/dxtest/dxtest.txt  --config ../../../utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

