name: Local
values:
  - key: baseUrl
    value: 'https://localhost:7738'
    enabled: true
  - key: basePath
    value: /hpc-server
    enabled: true
  - key: username
    value: '{{vault:username}}'
    enabled: true
  - key: password
    value: '{{vault:password}}'
    enabled: true
