name: Local
values:
  - key: baseUrl
    value: 'https://localhost:7738'
  - key: basePath
    value: /hpc-server
  - key: username
    value: '{{vault:username}}'
  - key: password
    value: '{{vault:password}}'
  - key: dataObjectPath
    value: FNL_SF_Archive/eran-pi-lab/eran-project/eran-flowcell/eran-sample/eran-data-object
