#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project 


#Clean previous results
./cleanme
$HPC_DM_TEST/utils/maketest
source $HPC_DM_TEST/utils/functions


USERID=$(get_username $HPC_DM_TEST/utils/config)

PROJECT_PATH="$(get_basefolder)/project-large-files"
register_collection_from_template "$PROJECT_PATH"
echo "$PROJECT_PATH" > registered-project-path.tmp
