#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


#Clean previous results
export DX_BASE_FOLDER_NAME=fs-base-folder
./cleanme
../utils/maketest-synchronous
