#!/usr/bin/env bash
# dm_add_bookmark 
# @author: Sunita Menon 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Add a new bookmark 

source $HPC_DM_UTILS/scripts/functions
dm_add_bookmark $@
