#!/usr/bin/env bash
# dm_download_collection
# @author: Yuri Dinh
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Download collecion to local directory 

source $HPC_DM_UTILS/scripts/functions
dm_download_collection $@
