#!/usr/bin/env bash
# dm_delete_collection 
# @author: Sunita Menon 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Delete a collection  

source $HPC_DM_UTILS/scripts/functions
dm_delete_collection $@
