#!/usr/bin/env bash
# dm_download_dataobject
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Download an object using presigned URL 

source $HPC_DM_UTILS/scripts/functions
dm_download_dataobject $@
