#!/usr/bin/env bash
# dm_list_commands
# @author: Yuri Dinh 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Show list of HPC DM Commands

source $HPC_DM_UTILS/scripts/functions
dm_list_commands $@
