#!/usr/bin/env bash
# dm_rename 
# @author: Sunita Menon
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Move/Rename a collection or data file.

source $HPC_DM_UTILS/scripts/functions
dm_rename $@
