#!/usr/bin/env bash
# dm_register_dataobject_multipart 
# @author: Yuri Dinh
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Register a dataobject using multi-part upload

source $HPC_DM_UTILS/scripts/functions
dm_register_dataobject_multipart "$@"
