#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

source $HPC_DM_TEST/utils/functions

#Clean previous results
./cleanme

#Call previous maketest
$HPC_DM_TEST/utils/maketest

#Register a query

#Create a unique string in the query

QUERY_ID=$(register_query_from_template)

echo "$QUERY_ID" > registered-query-id.tmp
