#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-user-groups/utils/runtest


#Verify that the group registration went through
GROUP_RESPONSE_HEADER=original_group_registration.tmp
mv group-registration-response-header.tmp  $GROUP_RESPONSE_HEADER 
verify_registration $GROUP_RESPONSE_HEADER 

#Get the new groupID
if ! [ -e new-group-id.tmp ] 
then
    echo "ERROR: The file new-user.id-tmp does not exist"
    exit 1
fi

NEW_USER=dxtest-invalid-user
NEW_GROUP=$(cat new-group-id.tmp)


RESPONSE_MSG=group-registration-response-message.json.tmp
RESPONSE_HEADER=group-registration-response-header.tmp

add_user_to_group  "$NEW_GROUP" "$NEW_USER"

RESPONSE_CODE=$(get_http_code "$RESPONSE_HEADER")
ERROR_TYPE=$(get_json_value "$RESPONSE_MSG" "errorType")


echo "$RESPONSE_CODE"
echo "$ERROR_TYPE"

