#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


#Clean previous results
./cleanme
$HPC_DM_TEST/utils/maketest

source $HPC_DM_TEST/utils/functions
source ../../utils/search-functions



#Give a unique name for the dataObject 

PREFIX="dxtest-data-name"
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
VALUE=$PREFIX-$SUFFIX
USERID=`get_username $HPC_DM_TEST/utils/config`
echo "$VALUE" > value.tmp

INPUT_TEMPLATE=../utils/register-dataobject.json
TEMPLATE=temp.tmp
update_uid "$INPUT_TEMPLATE"  "$TEMPLATE"
DESCRIPTION=`cat "$TEMPLATE" | sed "s/dxtest-data-name/$VALUE/" | sed "s/username/$USERNAME/"`

INPUT=`cat input.json | sed "s/dxtest-data-name/$VALUE/"`

echo "$DESCRIPTION" >  register-dataobject.json.tmp
echo "$INPUT" > input.json.tmp


register_project ../utils/register-project.json 
register_dataobject register-dataobject.json.tmp


