#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions



SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
QUERY_ID=queryid-$SUFFIX

register_query $QUERY_ID input.json

RESPONSE_HEADER=register-query-response-header.tmp
RESPONSE_MSG=register-query-response-message.json.tmp


HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2


RESPONSE_HEADER=get-query-response-header.tmp
RESPONSE_MSG=get-query-response-message.json.tmp

get_query  $QUERY_ID
HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

