#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


#Clean previous results
./cleanme
$HPC_DM_TEST/test-permission/utils/maketest

source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-permission/utils/functions

#TEMPLATE=$HPC_DM_TEST/test-permission/utils/register-user-template.json
register_user_from_template
#CODE=$(create_new_user $HPC_DM_TEST/test-permission/utils/register-user-template.json)
