#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


#Clean previous results
./cleanme

#Call previous maketest
$HPC_DM_TEST/utils/maketest
$HPC_DM_TEST/test-user-groups/utils/maketest


source $HPC_DM_TEST/utils/functions

#Register a user to add to the group
register-user-and-group
