#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


source $HPC_DM_TEST/utils/functions
#$HPC_DM_TEST/utils/runtest
../utils/runtest


#update a non existing bookmark 

collection_path=/$(get_basefolder)/dice_project1
sleep 1
suffix=`date +"%b-%d-%G-%H-%M-%S"`
bookmark_name=bookmark-$suffix
bookmark_group="new-bookmark-group"

response_hdr=update-bookmark-response-header.tmp
response_msg=update-bookmark-response-message.json.tmp

expected_msg="Bookmark name doesn't exist"
update_bookmark "$bookmark_name" "$collection_path" "$bookmark_group" "$response_hdr" "$response_msg"
get_http_code $response_hdr  >&2
get_json_value $response_msg errorType  >&2
get_json_value $response_msg message | sed "s@$expected_msg.*@$expected_msg@" >&2

