ALTER TABLE HPC_DATA_MIGRATION_TASK add (PERCENT_COMPLETE NUMBER(10), DATA_SIZE NUMBER(19));
COMMENT ON COLUMN HPC_DATA_MIGRATION_TASK.PERCENT_COMPLETE IS 'The migration percent complete';
COMMENT ON COLUMN HPC_DATA_MIGRATION_TASK.DATA_SIZE IS 'The size of the data. Applicable only for data object task type';

ALTER TABLE HPC_DATA_MIGRATION_TASK_RESULT add (DATA_SIZE NUMBER(19));
COMMENT ON COLUMN HPC_DATA_MIGRATION_TASK_RESULT.DATA_SIZE IS 'The size of the data. Applicable only for data object task type';
