#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


source $HPC_DM_TEST/utils/functions
#$HPC_DM_TEST/utils/runtest
../utils/runtest


#update a non existing bookmark 

sleep 1
suffix=`date +"%b-%d-%G-%H-%M-%S"`
bookmark_name=bookmark-$suffix

response_hdr=delete-bookmark-response-header.tmp
response_msg=delete-bookmark-response-message.json.tmp

expected_msg="Bookmark doesn't exist"
delete_bookmark "$bookmark_name"  "$response_hdr" "$response_msg"
get_http_code $response_hdr  >&2
get_json_value $response_msg errorType  >&2
get_json_value $response_msg message | sed "s@$expected_msg.*@$expected_msg@" >&2

