#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

query_by_metadata dataObject input.json 

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

ATTRIBUTE="\"name\""

#Check that the two object files are returned

VALUE="dice test data file 1"
RES=$(check_existance "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE" "TRUE")

VALUE="dice test data file 1"
RES=$(check_existance "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE" "TRUE")

VALUE="dice test sub1 data file 1"
RES=$(check_existance "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE" "FALSE")
