#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be deleted 

#Clean previous results
./cleanme
source $HPC_DM_TEST/utils/functions

#Register the base collection
ACTING_USER=dice_user_sys_admin
source $HPC_DM_TEST/test-delete/utils/register-base-collection

#Register a dataset 
project_path=$(cat registered-project-path.tmp)
sleep 1
name=`date +"%b-%d-%G-%H-%M-%S"`
dataset_path=${project_path}/test-${name}
curl_register input.json "$dataset_path" collection
echo $dataset_path > registered-dataset-path.tmp

update_single_permission  collection/"$project_path" dice_user OWN
