#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-user-groups/utils/runtest


register_group_from_template


RESPONSE_MSG=group-registration-response-message.json.tmp
RESPONSE_HEADER=group-registration-response-header.tmp

verify_registration "$RESPONSE_HEADER"


#Parse the response header. 

#Divide the output by {
SEPARATE_LINES=$(cat $RESPONSE_MSG | tr "{" "\n")
GROUP_RESPONSE=$(echo "$SEPARATE_LINES" | grep "\"group\"")


#Make sure the group is added "result true"
if ! [[ "$GROUP_RESPONSE" ==  *"\"result\":true"*  ]] 
then
    echo "ERROR: The group was not added correctly"
    exit
fi

