#!/usr/bin/env bash
# cleanme
# @author: William Liu 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to clean the results of this test
# Usage: cleanme [no arguments]

../../../utils/cleantest
../../utils/cleantest