#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

../utils/runtest

verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

#Delete the  collection
collection_path=$(cat registered-project-path.tmp)
RESPONSE_HEADER="delete-collection-response-header.tmp"
RESPONSE_MSG="delete-collection-response-message.json.tmp"

delete_collection "$collection_path" $RESPONSE_HEADER $RESPONSE_MSG

expected_msg="Collection is not empty"
get_http_code $RESPONSE_HEADER >&2
get_json_value $RESPONSE_MSG errorType  >&2
get_json_value $RESPONSE_MSG message | sed "s@^$expected_msg.*@$expected_msg@" >&2

