#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Clean previous results
source $HPC_DM_TEST/utils/functions
./cleanme

ACTING_USER=dice_user_sys_admin
#Register a new project
sleep 1
ACTING_USER=dice_user_sys_admin
NAME=$(date +"%b-%d-%G-%H-%M-%S")
PROJECT_PATH="$(get_basefolder)/project-permission-$NAME"
PROJECT_DESCRIPTION=project-metadata.json
curl_register $PROJECT_DESCRIPTION  $PROJECT_PATH collection
echo "$PROJECT_PATH" > registered-project-path.tmp

#Register a new-group
register_group_from_template

USER_ID=dice_user
NEW_GROUP_ID=$(cat new-group-id.tmp)

#Give READ permission to the new-group
update_group_permission collection/$PROJECT_PATH $NEW_GROUP_ID  READ


