#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


source $HPC_DM_TEST/utils/functions
#$HPC_DM_TEST/utils/runtest
../utils/runtest


#Verify add worked
response_hdr=add-bookmark-response-header.tmp
verify_registration $response_hdr

#update the bookmark
collection_path=/$(get_basefolder)/dice_project2
bookmark_name=$(cat bookmark-name.tmp)
bookmark_group="new-bookmark-group"

response_hdr=update-bookmark-response-header.tmp
response_msg=update-bookmark-response-message.json.tmp

update_bookmark "$bookmark_name" "$collection_path" "$bookmark_group" "$response_hdr" "$response_msg"
verify_registration $response_hdr

#Get the updated bookmark
response_hdr=get-bookmark-response-header.tmp
response_msg=get-bookmark-response-message.json.tmp

get_bookmark "$bookmark_name" "$response_hdr" "$response_msg"
RESPONSE_CODE=$(get_http_code $response_hdr)
echo $RESPONSE_CODE

#Verify the path is correct
path_exists=$(grep "$collection_path" $response_msg)
if [ -z "$path_exists" ]
then
    echo "ERROR: cannot find the path $collection_path in $response_msg" >&2
fi

#Verify the group is correct
group_exists=$(grep "$bookmark_group" $response_msg)
if [ -z "$group_exists" ]
then
    echo "ERROR: cannot find the group $bookmark_group in $response_msg" >&2
fi

if [ "$RESPONSE_CODE" -eq 200 ]
then
  delete_response_hdr=delete-bookmark-response-header.tmp
  delete_response_msg=delete-bookmark-response-message.json.tmp
  delete_bookmark "$bookmark_name" "$delete_response_hdr" "$delete_response_msg"
fi
