#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`

#Register the original dataOject
register_dataobject_async_from_template $PROJECT_PATH
verify_registration dataObject-registration-response-header.tmp
mv dataObject-registration-response-header.tmp orignial-dataObject-registration-response-header.tmp

if [ -e dataObject-registration-response-message.json.tmp ]
then
    mv dataObject-registration-response-message.json.tmp   original-dataObject-registration-response-message.json.tmp
fi


#Register the dataOject again
OBJECT_PATH=$(cat registered-data-object-path.tmp)
OBJECT_NAME=$(basename "$OBJECT_PATH")
register_dataobject_sync_from_template $PROJECT_PATH $OBJECT_NAME


RESPONSE_HEADER=dataObject-registration-response-header.tmp
RESPONSE_MSG=dataObject-registration-response-message.json.tmp

RETURN_CODE=`get_http_code $RESPONSE_HEADER`
RETURNED_ERROR_TYPE=`get_json_value $RESPONSE_MSG errorType`
RETURNED_MESSAGE=`get_json_value $RESPONSE_MSG message`


echo $RETURN_CODE >&2
echo $RETURNED_ERROR_TYPE >&2
echo $RETURNED_MESSAGE >&2

