#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Check if the collection and the dataObject registration functions called in makeme were successful.

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

search_by_metadata collection input.json dice_user_sys_admin

HTTP_CODE=`get_http_code $RESPONSE_HEADER`

if [ ! "$HTTP_CODE" -eq "200" ]  && [ ! "$HTTP_CODE" -eq "204" ]
then
    echo "ERROR: Got unexpected HTTP_CODE:$HTTP_CODE" >&2
fi

ATTRIBUTE="\"name\""

#Check that the two object files are returned

VALUE="prasad project1 sub1"
RES=$(check_existance "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE" "FALSE")
