#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be deleted 

#Clean previous results
./cleanme
../utils/maketest
source $HPC_DM_TEST/utils/functions

#Register the base collection
export DX_BASE_FOLDER_NAME=fs-base-folder
../utils/register-base-collection

#Register a dataObject synchronously 
PROJECT_PATH=$(cat registered-project-path.tmp)
register_dataobject_sync_from_template $PROJECT_PATH
