#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


RESPONSE_HEADER=metatadata-attributes-response-header.tmp
RESPONSE_MSG=metadata-attributes-response-message.json.tmp
get_metadata_attributes



HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE


#Parse the response message. 
PROJECT_OK=$(grep "\"Project\"" $RESPONSE_MSG)
FOLDER_OK=$(grep "\"Folder\"" $RESPONSE_MSG)
DATASET_OK=$(grep "\"Dataset\"" $RESPONSE_MSG)

if [ -z "$PROJECT_OK" ] 
then
    echo  "Project metadata not returned"
fi

if [ -z "$FOLDER_OK" ] 
then
    echo  "Folder metadata not returned"
fi

if [ -z "$DATASET_OK" ] 
then
    echo  "Dataset  metadata not returned"
fi

