#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


RESPONSE_HEADER=register-query-response-header.tmp
RESPONSE_MSG=register-query-response-message.json.tmp

HTTP_CODE=`get_http_code $RESPONSE_HEADER`

if [ ! "$HTTP_CODE" -eq "201" ]
then
    echo "Failed to register the query during makeme. " 
    exit
fi
    

REGISTERED_ID=$(cat registered-query-id.tmp)

RESPONSE_HEADER=update-query-response-header.tmp
RESPONSE_MSG=update-query-response-message.json.tmp

register_query $REGISTERED_ID input.json POST

#Verify the update request didn't go through 

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE  >&2

get_json_value $RESPONSE_MSG errorType >&2

