#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


#$HPC_DM_TEST/utils/runtest
../utils/runtest

source $HPC_DM_TEST/utils/functions

collection_path=/$(get_basefolder)/dice_project1

response_hdr=add-bookmark-response-header.tmp
response_msg=add-bookmark-response-message.json.tmp

add_bookmark_from_template "$collection_path"  "$response_hdr" "$response_msg"
get_http_code $response_hdr
