#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]

source $HPC_DM_TEST/utils/functions

#Clean previous files 
../../utils/cleantest

../../../utils/maketest
#Create policies file
../../utils/maketest dataObjectMetadataValidationRules

#Register a project to add dataObjects to it. 
#This does not follow the dummy DOC rules in ../../../../../../hpc-server/hpc-app-service-impl/src/main/resources/

PROJECT_DESTINATION_PATH="/FNL_SF_Archive/project-add-dataobject"
curl_register $HPC_DM_TEST/utils/templates/register-project-template.json "$PROJECT_DESTINATION_PATH" collection
echo "$PROJECT_DESTINATION_PATH" >> registered-project-path.tmp
