#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]

source $HPC_DM_TEST/utils/functions

#Clean previous files 
../../utils/cleantest

../../../utils/maketest
#Create policies file
../../utils/maketest dataObjectMetadataValidationRules

#Register a project to add dataObjects to it. 
#This does not follow the dummy DOC rules in ../../../../../../hpc-server/hpc-app-service-impl/src/main/resources/

PROJECT_DESTINATION_PATH="$(get_basefolder)/project-add-dataobject"
curl_register $HPC_DM_TEST/utils/templates/register-project-template.json "$PROJECT_DESTINATION_PATH" collection
mv $RESPONSE_HEADER project-response-header.tmp  
mv $RESPONSE_MSG project-response-message.json.tmp 2>/dev/null


RUN_PATH=$PROJECT_DESTINATION_PATH/test-run
curl_register input-run.json "$RUN_PATH" collection
mv $RESPONSE_HEADER run-response-header.tmp  
mv $RESPONSE_MSG run-response-message.json.tmp 2>/dev/null

echo "$PROJECT_DESTINATION_PATH" >> registered-project-path.tmp
echo "$RUN_PATH" >> registered-run-path.tmp

