#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions
source ../../../utils/functions
sleep 1
NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username ../../../utils/config`
#../../utils/registration-runtest collection $(get_basefolder)/test-${NAME} 
#../../utils/registration-runtest collection $(get_basefolder)/${USERID}/dice-unit-test/test-${NAME} 
../../utils/registration-runtest collection $(get_basefolder)/test-${NAME} 
