#!/usr/bin/env bash
# -------------------------------------------------------------------------
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
# -------------------------------------------------------------------------

# Common script to clean a test
# Usage: cleantest [no arguments]

rm -rf response-message.json response-header error curl-status 2/dev/null 2> curl-status 
