#!/usr/bin/env bash
# runtest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Common script to run tests 


if [ ! -f input.json ]; then
    echo "No input.json file"
    exit
fi 



