#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-user-groups/utils/runtest


#Check that the group registration went through 
RESPONSE_MSG=group-registration-response-message.json.tmp
RESPONSE_HEADER=group-registration-response-header.tmp

verify_registration $RESPONSE_HEADER


RESPONSE_MSG=group-update-response-message.json.tmp
RESPONSE_HEADER=group-update-response-header.tmp
group_name=$(cat new-group-id.tmp)

update_group input.json "$group_name" $RESPONSE_HEADER $RESPONSE_MSG 

HTTP_CODE=$(get_http_code $RESPONSE_HEADER)
echo $HTTP_CODE >&2

if [ "$HTTP_CODE" = "400" ]
then
    ERROR_TYPE=$(get_json_value $RESPONSE_MSG errorType)
    ERROR_MSG=$(get_json_value $RESPONSE_MSG message)
    
    echo "$ERROR_TYPE" >&2
    echo "$ERROR_MSG" >&2
fi

