#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


#Clean previous results
./cleanme

#Call previous maketest
$HPC_DM_TEST/utils/maketest
$HPC_DM_TEST/test-notifications/utils/maketest

source $HPC_DM_TEST/utils/functions

RESPONSE_HEADER=subscribe-notifications-response-header.tmp
RESPONSE_MSG=subscribe-notifications-response-message.json.tmp

subscribe_to_template_notifications

#Register the base collection
../utils/register-base-collection

#Register a dataObject asynchronously 
PROJECT_PATH=$(cat registered-project-path.tmp)
register_dataobject_async_from_template $PROJECT_PATH

