#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest


verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp


FOLDER_PATH=collection/$(cat registered-folder-path.tmp)


RESPONSE_HEADER=download-response-header.tmp 
RESPONSE_MSG=download-response-message.json.tmp
download_async "$FOLDER_PATH"



HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo "download-request $HTTP_CODE"

#Do not check the file if the code is not 200
if [ $HTTP_CODE != 200 ] 
then
    exit
fi


#Make sure a task ID is returned
taskId=$(get_json_value $RESPONSE_MSG taskId)
if [[ -z "$taskId" ]] 
then
  echo "Can not find taskID in $RESPONSE_MSG" >&2;
  exit 1
fi

sleep 100

FOLDER_PATH=$(get_json_value input.json.tmp fileId)
FILE_ID=$(basename $(cat registered-dataobject-path.tmp))

verify_globus_download "$taskId"  "$FOLDER_PATH/$FILE_ID" "collection"
