#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`

OBJECT_PATH=$PROJECT_PATH/object-${NAME}.txt

#Create an object file
OBJECT_FILE=object.tmp
echo "Hello" >  $OBJECT_FILE 
curl_register input.json "$OBJECT_PATH" dataObject "$OBJECT_FILE"

response_header=dataObject-registration-response-header.tmp

verify_registration $response_header
verify_location "$response_header" "$OBJECT_PATH"
