#!/usr/bin/env bash
# runme
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
source ../../utils/registration-functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`

DATAOBJECT_PATH="${PROJECT_PATH}/object-${SUFFIX}.txt"

#Register the collection 
curl_register input.json  "$DATAOBJECT_PATH" dataObject 

#Check the returned code is 201
REG_HTTP_CODE=`get_http_code dataObject-registration-response-header.tmp`
if [ "$REG_HTTP_CODE" != "201" ]  
then
        echo "FAILED TO REGISTER DATAOBJECT, HTTP_CODE = $REG_HTTP_CODE" 1>&2
        exit
fi

mv dataObject-registration-response-header.tmp original-registration-header.tmp
echo $REG_HTTP_CODE


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

#Get the registered dataObject by path
get_item "/dataObject/${DATAOBJECT_PATH}" "$RESPONSE_HEADER" "$RESPONSE_MSG"

GET_HTTP_CODE=`get_http_code $RESPONSE_HEADER`
if [ "$GET_HTTP_CODE" != "200" ]  
then
        echo "FAILED TO GET, HTTP_CODE = $GET_HTTP_CODE" 1>&2
        exit
fi



ATTRIBUTE="\"uuid\""
check_attribute "$RESPONSE_MSG" "$ATTRIBUTE"

ATTRIBUTE="\"registered_by_name\""
check_attribute "$RESPONSE_MSG" "$ATTRIBUTE"

ATTRIBUTE="\"registered_by_doc\""
check_attribute "$RESPONSE_MSG" "$ATTRIBUTE"


