#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`

curl_register input.json $PROJECT_PATH/object-${NAME}.txt dataObject

EXPECTED_MSG="\[GLOBUS\] Endpoint doesn't exist. Make sure the endpoint name is correct and active"
get_http_code $RESPONSE_HEADER >&2
get_json_value $RESPONSE_MSG errorType >&2
get_json_value $RESPONSE_MSG message | sed "s/^$EXPECTED_MSG.*/$EXPECTED_MSG/" >&2
