
-- HPC_COLLECTION_DOWNLOAD_TASK
ALTER TABLE HPC_COLLECTION_DOWNLOAD_TASK add (RETRY_USER_ID VARCHAR2(250)); 
COMMENT ON COLUMN HPC_COLLECTION_DOWNLOAD_TASK.RETRY_USER_ID IS 'The User ID of User who re-tried the task';

-- HPC_DATA_OBJECT_DOWNLOAD_TASK
ALTER TABLE HPC_DATA_OBJECT_DOWNLOAD_TASK add (RETRY_USER_ID VARCHAR2(250)); 
COMMENT ON COLUMN HPC_DATA_OBJECT_DOWNLOAD_TASK.RETRY_USER_ID IS 'The User ID of User who re-tried the task';

-- HPC_DOWNLOAD_TASK_RESULT
ALTER TABLE HPC_DOWNLOAD_TASK_RESULT add (RETRY_USER_ID VARCHAR2(250)); 
COMMENT ON COLUMN HPC_DOWNLOAD_TASK_RESULT.RETRY_USER_ID IS 'The User ID of User who re-tried the task';
