#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest


verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

OBJECT_PATH=`cat registered-dataobject-path.tmp`

FILE_NAME=$(basename $OBJECT_PATH)
INPUT_JSON=$(cat input.json | sed "s/dxfilename/$FILE_NAME/")
echo "$INPUT_JSON" > input.json


RESPONSE_HEADER=download-response-header.tmp 
RESPONSE_MSG=download-response-message.json.tmp
download_dataobject_sync "$OBJECT_PATH"

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

get_json_value $RESPONSE_MSG  errorType >&2
get_json_value $RESPONSE_MSG  requestRejectReason >&2

