#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]


#$HPC_DM_TEST/utils/runtest
../utils/runtest

source $HPC_DM_TEST/utils/functions

#Verify add worked
collection_path=/$(get_basefolder)/dice_project1
response_hdr=add-bookmark-response-header.tmp
verify_registration $response_hdr

#get the bookmark
bookmark_name=$(cat bookmark-name.tmp)
bookmark_group=$(cat bookmark-group.tmp)
response_hdr=get-bookmark-response-header.tmp
response_msg=get-bookmark-response-message.json.tmp

get_bookmarks "$response_hdr" "$response_msg"
RESPONSE_CODE=$(get_http_code $response_hdr)
echo $RESPONSE_CODE

#Verify the bookmark exists
name_exists=$(grep "$bookmark_name" $response_msg)
if [ -z "$name_exists" ]
then
    echo "ERROR: cannot find the bookmark $bookmark_name in $response_msg" >&2
fi

if [ "$RESPONSE_CODE" -eq 200 ]
then
  delete_response_hdr=delete-bookmark-response-header.tmp
  delete_response_msg=delete-bookmark-response-message.json.tmp
  delete_bookmark "$bookmark_name" "$delete_response_hdr" "$delete_response_msg"
fi

