--
-- hpc_data_object_registration_google_access_token.sql
--
-- Copyright Leidos Biomedical Research, Inc
-- 
-- Distributed under the OSI-approved BSD 3-Clause License.
-- See http://ncip.github.com/HPC/LICENSE.txt for details.
--
--
-- @author <a href="mailto:eran.rosenberg@nih.gov">Eran Rosenberg</a>
--

ALTER TABLE HPC_DATA_OBJECT_REGISTRATION_GOOGLE_ACCESS_TOKEN DROP COLUMN ACCESS_TOKEN_TYPE;
ALTER TABLE HPC_DATA_OBJECT_DOWNLOAD_TASK DROP COLUMN ACCESS_TOKEN_TYPE;
ALTER TABLE HPC_COLLECTION_DOWNLOAD_TASK DROP COLUMN ACCESS_TOKEN_TYPE;

ALTER TABLE HPC_COLLECTION_DOWNLOAD_TASK add (GOOGLE_DRIVE_ACCESS_TOKEN BLOB); 
COMMENT ON COLUMN  HPC_COLLECTION_DOWNLOAD_TASK.GOOGLE_DRIVE_ACCESS_TOKEN IS 'Google drive access token';  

ALTER TABLE HPC_COLLECTION_DOWNLOAD_TASK add (GOOGLE_CLOUD_ACCESS_TOKEN BLOB); 
COMMENT ON COLUMN  HPC_COLLECTION_DOWNLOAD_TASK.GOOGLE_CLOUD_ACCESS_TOKEN IS 'Google cloud access token';  


