#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest

verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

OBJECT_PATH=`cat registered-dataobject-path.tmp`

#Download the dataobject synchronously
RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
download_dataobject_sync "$OBJECT_PATH"

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

#Do not check the file is the code is not 200
if [ $HTTP_CODE != 200 ] 
then
    exit
fi

#Make sure the file exists with the correct string
diff  dataObject-file.tmp "$RESPONSE_MSG"
