#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../utils/runtest


RESPONSE_HEADER=get-object-response-header.tmp
RESPONSE_MSG=get-object-response-message.json.tmp

ITEM_PATH=dataObject/`get_basefolder`/dice_project1/dice_object_1
get_item $ITEM_PATH  $RESPONSE_HEADER $RESPONSE_MSG
#Check if collection registration went through:



#Check if the unit is part of the returned metadata
UNIT_EXIST=$(grep  dxtest-unit $RESPONSE_MSG)

if [ -z "$UNIT_EXIST" ]
then
    echo "Failed to find the unit in the parent metadata $RESPONSE_MSG" >&2
fi

