#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username "$HPC_DM_TEST/utils/config"`
COLLECTION_PREFIX="/FNL_SF_Archive/${USERID}/dice-unit-test/test-batch-${NAME}"

PROJECT_PATH="$COLLECTION_PREFIX-project/"
DATASET_PATH="$COLLECTION_PREFIX-dataset/"
FOLDER_PATH="$COLLECTION_PREFIX-folder/"

UPDATED_PROJECT=`cat input.csv | sed "s#\<project-path\>#$PROJECT_PATH#"`
UPDATED_DATASET=`echo "$UPDATED_PROJECT" | sed "s#\<dataset-path\>#$DATASET_PATH#"`
UPDATED_FOLDER=`echo "$UPDATED_DATASET" | sed "s#\<folder-path\>#$FOLDER_PATH#"`

echo "$UPDATED_FOLDER" > input.csv.tmp

#Register the collection in a batch mode 
java  -Dhpc.client.properties=$HPC_DM_TEST/test-hpc-client/utils/hpc-client/hpc.properties -jar $HPC_DM_CLIENT --cmdfile ./batch_cmd.txt >batch-log.tmp 2>batch-error-log.tmp


REGISTERED_COLLECTIONS="$PROJECT_PATH $DATASET_PATH $FOLDER_PATH"

for collection in $REGISTERED_COLLECTIONS; do

    RESPONSE_HEADER=response-header.tmp
    RESPONSE_MSG=response-message.json.tmp
    #Get the registered collection by path

    curl -G -X GET $SERVER/hpc-server/collection/${collection}  --config $HPC_DM_TEST/utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 

    GET_HTTP_CODE=`get_http_code $RESPONSE_HEADER`
    if [ "$GET_HTTP_CODE" != "200" ]  
        then
            echo "FAILED TO GET $collection, HTTP_CODE = $GET_HTTP_CODE" 1>&2
        exit
    fi
done
