#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Run common script
$HPC_DM_TEST/utils/runtest

#Clean previous results
#./cleanme

SERVER=`cat $HPC_DM_TEST/utils/server`


register_user_from_template
NEW_USER_ID=$(cat new-user-id.tmp)

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
enroll_user $NEW_USER_ID  input.json $RESPONSE_HEADER $RESPONSE_MSG

ERROR_TYPE=`get_json_value $RESPONSE_MSG errorType`
ERROR_REASON=`get_json_value $RESPONSE_MSG requestRejectReason`
ERROR_CODE=`get_http_code $RESPONSE_HEADER`

echo $ERROR_CODE 1>&2
echo $ERROR_TYPE 1>&2
echo $ERROR_REASON 1>&2
