#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Clean previous results
./cleanme


source ../../../utils/functions

USER=`get_username ../../../utils/config`
DESTINATION_PATH="/$USER/random/path"
curl_register ../utils/project-description.json "$DESTINATION_PATH" collection

echo "$DESTINATION_PATH" > path.tmp
