#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest


SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
OBJECT_PATH=`cat path.tmp`
OBJECT_PATH="$OBJECT_PATH-$SUFFIX"
curl_register input.json  "$OBJECT_PATH" dataObject

RESPONSE_HEADER=dataObject-registration-response-header.tmp
RESPONSE_MSG=dataObject-registration-response-message.json.tmp

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
ERROR_TYPE=$(get_json_value "$RESPONSE_MSG" "errorType") 
ERROR_REASON=$(get_json_value "$RESPONSE_MSG" "requestRejectReason") 

echo $HTTP_CODE 1>&2
echo $ERROR_TYPE 1>&2
echo $ERROR_REASON 1>&2

