#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common script to make  to register a collection
# Usage: maketest 


source $HPC_DM_TEST/utils/functions
USERID=`get_username $HPC_DM_TEST/utils/config`
DESTINATION_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-add-dataobject"
echo "$DESTINATION_PATH" >> registered-project-path.tmp
curl_register $HPC_DM_TEST/test-register/test-dataObject-registration/utils/project-description.json "$DESTINATION_PATH" collection
