#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common script to make  to register a collection
# Usage: maketest 


source $HPC_DM_TEST/utils/functions
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_DESTINATION_PATH="/FNL_SF_Archive/project-add-dataobject"
FOLDER_DESTINATION_PATH="/FNL_SF_Archive/project-add-dataobject/folder-collection"
#DESTINATION_PATH="/FNL_SF_Archive/${USERID}/dice-unit-test/project-add-dataobject"
curl_register $HPC_DM_TEST/utils/templates/register-project-template.json "$PROJECT_DESTINATION_PATH" collection
mv collection-registration-response-header.tmp project-registration-response-header.tmp
if [ -e collection-registration-response-message.tmp  ]
then 
    mv collection-registration-response-message.tmp project-registration-response-message.tmp
fi

curl_register $HPC_DM_TEST/utils/templates/register-folder-template.json "$FOLDER_DESTINATION_PATH" collection
echo "$FOLDER_DESTINATION_PATH" >> registered-project-path.tmp
