#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../../utils/functions
source ../../utils/search-functions

#Check if the collection and the dataObject registration functions called in makeme were successful.
check_registration
check_dataobject_registration

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat ../../../utils/server`

curl -G -X GET $SERVER/hpc-server/dataObject --data-urlencode metadataQuery@input.json.tmp  --config ../../../utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
check_connection $RESPONSE_HEADER

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

ATTRIBUTE="\"name\""
VALUE=`cat value.tmp`

#Make sure the response does not include the object
RESPONSE_GROUPS=`cat $RESPONSE_MSG | tr "{" "\n"`
OBJECT_GROUPS=`echo "$RESPONSE_GROUPS" | grep "$ATTRIBUTE"`
OBJECT_NAMES=`get_json_value "$OBJECT_GROUPS" value`


OBJECT_FOUND="FALSE"
for object in $OBJECT_NAMES; do
    if [[ $object == *"$VALUE"*  ]]
    then
        OBJECT_FOUND="TRUE"
        break
    fi
done 

if [ "$OBJECT_FOUND" == "TRUE" ] 
then
    echo "ERROR: OBJECT \"$VALUE\" IS PART OF THE RESULTS."  1>&2
fi
