                 
ALTER TABLE HPC_DATA_MANAGEMENT_CONFIGURATION add (
	DELETION_ALLOWED_AFTER_90_DAYS CHAR default '0',
	RESTRICT_METADATA CHAR default '0'
	);
COMMENT ON COLUMN HPC_DATA_MANAGEMENT_CONFIGURATION.DELETION_ALLOWED_AFTER_90_DAYS IS 'Indicator if deletion is allowed after 90 days';
COMMENT ON COLUMN HPC_DATA_MANAGEMENT_CONFIGURATION.RESTRICT_METADATA IS 'Indicator if metadata should be pre-declared in the validation rules';

