#!/usr/bin/env bash
# functions
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common functions used by the update user unit tests 

#Update the user 
function update_user {

    #Verify that makeme registration went through 

    RESPONSE_HEADER=user-registration-response-header.tmp
    RESPONSE_MSG=user-registration-response-message.json.tmp
    REGISTRATION_RESPONSE_CODE=`get_http_code $RESPONSE_HEADER`
    
    if [ "$REGISTRATION_RESPONSE_CODE" != "201" ]
    then
        echo "ERROR: Unsuccessful user registration" 1>&2
        exit
    fi
    
    RESPONSE_HEADER=response-header
    RESPONSE_MSG=response-message.json
    
    USER_ID=$(cat new-user-id.tmp)
    SERVER=`cat $HPC_DM_TEST/utils/server`

    update_existing_user $USER_ID input.json $RESPONSE_HEADER $RESPONSE_MSG    
    #curl -H "Content-Type: application/json" -d @input.json -X POST ${SERVER}/user/$USER_ID  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
    #check_connection $RESPONSE_HEADER
}


