#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
sleep 1
NAME=`date +"%b-%d-%G-%H-%M-%S"`
PROJECT_PATH=$(get_basefolder)/project-${NAME}
NEW_FOLDER_PATH=$PROJECT_PATH/folder-${NAME}

curl_register input-template.json $NEW_FOLDER_PATH collection 

get_http_code $RESPONSE_HEADER
