#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions



source $HPC_DM_TEST/utils/functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

sleep 1
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`

OBJECT_FILE=dataobject-${SUFFIX}.tmp
echo "data-$NAME" > $OBJECT_FILE

PROJECT_PATH=`cat registered-project-path.tmp`

#Register the original dataOject

curl_register input-md5sum.json $PROJECT_PATH/$OBJECT_FILE dataObject data-file.txt  
verify_registration dataObject-registration-response-header.tmp
