#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]


#Clean previous parsed policies file
../../utils/cleantest

#Common maketest 
$HPC_DM_TEST/utils/maketest

#Register a collection
../utils/maketest
