#!/usr/bin/env bash
# runme
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions
source ../../../utils/functions

#Check the project registraiton went through

verify_registration project-registration-response-header.tmp 

REGISTERED_PROJECT=$(cat registered-project.tmp)

sleep 1

curl_register input.json "$REGISTERED_PROJECT" collection

get_http_code "$RESPONSE_HEADER" >&2 
get_json_value  "$RESPONSE_MSG" "errorType" >&2
get_json_value  "$RESPONSE_MSG" "message" >&2
#../../utils/registration-runtest collection ${REGISTERED_PROJECT}/test-${NAME} 
