#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../../utils/functions
source ../../utils/search-functions

#Check if the register_project function called in makeme was successful.
check_registration


USERID=`get_username ../../../utils/config`

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
SERVER=`cat ../../../utils/server`

REGISTERED_PROJECT=`cat registered-project-name`

curl -G -X GET $SERVER/hpc-server/collection/${REGISTERED_PROJECT} --data-urlencode metadataQuery@input.json  --config ../../../utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE

ATTRIBUTE="name"
VALUE="dxtest-project-name"

#Make sure the response does not include the project named "dxtest-project-name".
RESPONSE_GROUPS=`cat $RESPONSE_MSG | tr "{" "\n"`
PROJECT_GROUPS=`echo "$RESPONSE_GROUPS" | grep "$ATTRIBUTE"`
PROJECT_NAMES=`get_json_value "$PROJECT_GROUPS" value`

PROJECT_FOUND="FALSE"
for project in $PROJECT_NAMES; do
    if [[ $project == *"$VALUE"*  ]]
    then
        PROJECT_FOUND="TRUE"
        break
    fi
done 

if [ "$PROJECT_FOUND" == "FALSE" ] 
then
    echo "ERROR: PROJECT \"dxtest-project-name\" IS NOT PART OF THE RESULTS."  1>&2
fi
