                 
ALTER TABLE HPC_DATA_MANAGEMENT_CONFIGURATION add (REGISTRATION_EVENT_WITH_DOWNLOAD_REQUEST_URL CHAR default '0');
COMMENT ON COLUMN HPC_DATA_MANAGEMENT_CONFIGURATION.REGISTRATION_EVENT_WITH_DOWNLOAD_REQUEST_URL IS 'Indicator if a download URL should be created with a registration completion event';

