#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest


verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

OBJECT_PATH=`cat registered-dataobject-path.tmp`

FILE_NAME=$(basename $OBJECT_PATH)
INPUT_JSON=$(cat input.json | sed "s/dxfilename/$FILE_NAME/")
echo "$INPUT_JSON" > input.json


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
download_dataobject_async "$OBJECT_PATH" "input.json"


HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2


EXPECTED_MSG="Destination file location not accessible"
get_json_value $RESPONSE_MSG errorType >&2
get_json_value $RESPONSE_MSG message | sed "s/^$EXPECTED_MSG.*/$EXPECTED_MSG/"  >&2
#Do not check the file is the code is not 200
#if [ $HTTP_CODE != 200 ] 
#then
#    exit
#fi
#
#GLOBUS_PATH=$(get_json_value input.json fileId)
#verify_globus_file  $GLOBUS_PATH
