#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
#source $HPC_DM_TEST/test-search/utils/search-functions

#Check if the collection registration function called in makeme was successful.
#check_registration

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

query_by_metadata collection input.json dice_user_sys_admin
RES=$(check_non_existance "$RESPONSE_HEADER" "$RESPONSE_MSG" "$ATTRIBUTE" "$VALUE")  

