#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project   

PERMISSION_UTILS=$HPC_DM_TEST/test-permission/utils/

source $HPC_DM_TEST/utils/functions
source $PERMISSION_UTILS/functions


#Clean previous results
./cleanme

#Call general maketest
$HPC_DM_TEST/utils/maketest


#Register the dataOjbect
#update_uid ../utils/register-dataobject.json register-dataobject.json.tmp
#NAME=`date +"%b-%d-%G-%H-%M-%S"`
#DESTINATION_PATH=${PROJECT_PATH}/object-${NAME}.txt
#echo "$DESTINATION_PATH" > registered-dataobject-path.tmp
#curl_register register-dataobject.json.tmp  "$DESTINATION_PATH" dataObject
