#!/usr/bin/env bash
# functions
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Common functions to access the API.



source $HPC_DM_UTILS/utilities

#Generate a DM API authentication token
function dm_generate_token {

    LOG_FILE=$HPC_DM_UTILS/log
    rm $LOG_FILE 2>/dev/null

    SERVER=$(get_server)
    
    curl -k -u `get_username` ${SERVER}/authenticate >  $LOG_FILE
    TOKEN=$(get_json_value $LOG_FILE token)

    if [ -z $TOKEN ]
    then
        echo "ERROR: no token found in $LOG_FILE " >&2
        MESSAGE=$(get_json_value $LOG_FILE message)
        echo "ERROR MESSAGE: $MESSAGE"   
        return
    else  
      CONFIG_STRING=$(cat "$HPC_DM_UTILS/curl-conf" | sed "s/Bearer.*/Bearer $TOKEN\"/")
      echo "$CONFIG_STRING" > $HPC_DM_UTILS/curl-conf
      rm $LOG_FILE 2>/dev/null
    fi
}

#Generate a Globus authentication token
function dm_globus_generate_token {

    LOG_FILE=$HPC_DM_UTILS/log-globus
    rm $LOG_FILE 2>/dev/null

    SERVER=$(get_globus_server)
    GLOBUS_USER=$(get_globus_user)
    
    curl -u $GLOBUS_USER ${SERVER}/goauth/token?grant_type=client_credentials -s  >  $LOG_FILE
    TOKEN=$(get_json_value $LOG_FILE access_token)

    if [ -z $TOKEN ]
    then
        echo "ERROR: no token found in $LOG_FILE " >&2
        MESSAGE=$(get_json_value $LOG_FILE message)
        echo "ERROR MESSAGE: $MESSAGE"   
        return 
    else  
        GLOBUS_CONFIG=$(cat "$HPC_DM_UTILS/curl-globus" | sed "s@Bearer.*@Bearer $TOKEN\"@")
        echo "$GLOBUS_CONFIG" > $HPC_DM_UTILS/curl-globus
        rm $LOG_FILE 2>/dev/null
    fi
}




#Register a collection or a dataObject 
#Inputs:  <description.json>: The metadata json file 
#         <destinaton-path>: The logical path of the destination
#         <type>: dataObjet or collection 
#         [data-object-file] : For synchronous dataObject registration only
function dm_register {

    USAGE="USAGE: dm_register <description.json> <destination-path> <colleciton|dataObject> [data-object-file]"

    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
    then
        echo "ERROR: using dm_register" >&2
        echo "Received: $@" >&2
        echo "$USAGE" >&2
        return
    fi


    if [ ! -z "$4" ]
    then
        DATAOBJECT_FILE="$4"
        if [ ! -e "$DATAOBJECT_FILE" ]
        then 
            echo "ERROR: The data-object-file:$DATAOBJECT_FILE does not exist " >&2
            return
        fi
    fi
        
    DESCRIPTION="$1"
    DESTINATION_PATH="$2"
    TYPE="$3"
    USERID=$(get_username)
    SERVER=$(get_server)

    CONFIG="--config $HPC_DM_UTILS/curl-conf"
    
    RESPONSE_MSG=${TYPE}-registration-response-message.json.tmp
    RESPONSE_HEADER=${TYPE}-registration-response-header.tmp

    rm $RESPONSE_MSG 2>/dev/null 
    rm $RESPONSE_HEADER 2>/dev/null 

    CURL_FLAGS="-X PUT ${SERVER}/${TYPE}/${DESTINATION_PATH}  $CONFIG  -D $RESPONSE_HEADER -o $RESPONSE_MSG "
   
    if [ "$TYPE" == "dataObject" ]
    then
        if [ -z "$DATAOBJECT_FILE" ]
        then
            curl -F "dataObjectRegistration=@$DESCRIPTION;type=application/json" $CURL_FLAGS -H "Accept: application/json"  2> curl-status
        else
            curl -F "dataObjectRegistration=@$DESCRIPTION;type=application/json" -F "dataObject=@$DATAOBJECT_FILE;type=application/octet-stream" $CURL_FLAGS  -H "Accept: application/json"  2> curl-status 
        fi
    elif [ "$TYPE" == "collection" ]
    then

           curl -H "Content-Type: application/json" -d @$DESCRIPTION $CURL_FLAGS  -H "Accept: application/json" 2>curl-status
    else
        echo "ERROR: Unsupported registration type:$TYPE"
        return 
    fi
    check_connection $RESPONSE_HEADER
}

#Register a collection 
#Inputs:  <description.json>: The metadata json file for the collection 
#         <destinaton-path>: The destination logical path
function dm_register_collection {

    USAGE="USAGE: dm_register_collection <description.json> <destination-path>"

    if [ -z "$1" ] || [ -z "$2" ] 
    then
        echo "ERROR: using dm_register_collection" >&2
        echo "Received: $@" >&2
        echo "$USAGE" >&2
        return
    fi

    DESCRIPTION="$1"
    DESTINATION_PATH="$2"
    dm_register $DESCRIPTION $DESTINATION_PATH collection

    RESPONSE_HEADER=collection-registration-response-header.tmp
    RESPONSE_MSG=collection-registration-response-message.json.tmp

    verify_registration "$RESPONSE_HEADER" "$RESPONSE_MSG" "$DESTINATION_PATH"

}


#Register a dataObject 
#Inputs:  <description.json>: The metadata json file for the dataObject 
#         <destinaton-path>: The destination logical path
#         [source-file]: The source file for synchronous registratio.
function dm_register_dataobject {

    USAGE="USAGE: dm_register_dataobject <description.json> <destination-path> [source-file]"

    if [ -z "$1" ] || [ -z "$2" ] 
    then
        echo "ERROR: using dm_register_collection" >&2
        echo "Received: $@" >&2
        echo "$USAGE" >&2
        return
    fi

    DESCRIPTION="$1"
    DESTINATION_PATH="$2"
    SOURCE_FILE="$3"
    dm_register "$DESCRIPTION" "$DESTINATION_PATH" dataObject "$SOURCE_FILE" 

    RESPONSE_HEADER=dataObject-registration-response-header.tmp
    RESPONSE_MSG=dataObject-registration-response-message.json.tmp

    verify_registration "$RESPONSE_HEADER" "$RESPONSE_MSG" "$DESTINATION_PATH"
}

#Sync a folder in the current file system with a logical path in the Archive
#There is no metadata for folder and they will be automatically created.
#The files metadata is the list of attributes/values pair that are returned by the 
#function "get_json-file"
#Inputs: Globus endpoint
#        Source path on Globus endpoint
#        Destination logical path on Archive.
#<source-folder>    The source folder on the file system
#        <destination-path> The destination logical path
function dm_sync_globus_endpoint  {

    USAGE="USAGE: dm_sync_folder <source-folder> <destination-path>"

    if [ -z "$1" ] || [ -z "$2" ] 
    then
        echo "ERROR: using dm_register_collection" >&2
        echo "Received: $@" >&2
        echo "$USAGE" >&2
        return
    fi


    RESPONSE_HEADER=dataObject-registration-response-header.tmp
    RESPONSE_MSG=dataObject-registration-response-message.json.tmp


    FILE_LIST="./test.txt /TEST_Archive/test.txt"

    while read -r  NEW_FILE 
    do 

      SRC_PATH=$(echo $NEW_FILE | cut -d' ' -f1)
      DST_PATH=$(echo $NEW_FILE | cut -d' ' -f2)

      FILE_ATTRIBUTES=$(get_file_attributes $SRC_PATH)      
      DESC_JSON=$(get_json_description $FILE_ATTRIBUTES)
      echo $DESC_JSON >  temp.json
      echo "dm_register_dataobject  temp.json $DST_PATH $SRC_PATH"
      echo "verify_registration  $REPONSE_HEADER $RESPONSE_MSG $DST_PATH"

      rm $RESPONSE_HEADER 2>/dev/null
      rm $RESPONSE_MSG 2>/dev/null

    done <<< "$FILE_LIST"

}


#Get an item (collection or dataObject) from the archive
#Inputs: <item-path> (should have a prefix of "dataObject" or "collection:)
#      : [response-message-filename]
#      : [response-header-filename]
function dm_get_item {

    USAGE="dm_get_item  <item-path> [response-message-filename] [response-header-filename]"

    if [ "$#" -lt 1 ] 
    then
        echo "ERROR: using dm_get_item" >&2
        echo "$USAGE" >&2
        return
    fi
    ITEM_PATH="$1"

    if [ ! -z "$2" ]
    then
      RESONSE_MSG="$2"
    else
      RESPONSE_MSG=get-item-response-message.json.tmp
    fi 

    if [ ! -z "$3" ]
    then
      RESONSE_HEADER="$3"
    else
      RESPONSE_HEADER=get-item-response-header.tmp
    fi 

    CONFIG="--config $HPC_DM_UTILS/curl-conf"
        
    SERVER=$(get_server)

    TOTAL_PATH="$ITEM_PATH"
    TOTAL_PATH=$(echo "$TOTAL_PATH" | sed "s#\/\/*#\/#g")
   
    curl -G -X GET "$SERVER/$TOTAL_PATH"  $CONFIG  -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
    check_connection $RESPONSE_HEADER
}


#Get the metadata of a dataobject from the archive
#Inputs: <dataObject-path> 
#      : [response-message-filename]
#      : [response-header-filename]
function dm_get_dataobject {

    USAGE="dm_get_item_dataobject  <dataobject-path> [response-message-filename] [response-header-filename]"

    if [ "$#" -lt 1 ] 
    then
        echo "ERROR: using get_dataobject" >&2
        echo "recieved $0 $@" 
        echo "$USAGE" >&2
        return
    fi
    ITEM_PATH="$1"


    RESPONSE_MSG=${2-get-item-response-message.json.tmp}
    RESPONSE_HEADER=${3-get-item-response-header.tmp}

    dm_get_item dataObject/$ITEM_PATH  "$RESPONSE_MSG" "$RESPONSE_HEADER"

    RESPONSE_CODE=$(get_http_code $RESPONSE_HEADER)
    if [ "$RESPONSE_CODE" -ne 200 ]
    then
      echo "ERROR getting \"$ITEM_PATH\" " >&2
      echo "ERROR_CODE:\"$RESPONSE_CODE\"" >&2
      print_error_message "$RESPONSE_MSG" "$REPONSE_CODE"
      return 1
    else 
     
      #Check if the user needs the response header file 
      if [ -z "$3" ]
      then 
        rm "$RESPONSE_HEADER" 2> /dev/null
      fi

      if [ -z "$2" ]
      then
        print_json_message "$RESPONSE_MSG"    
        rm $RESPONSE_MSG 2> /dev/null 
      fi
      return 0
    fi
    return 1
}


#Get the metadata of a collection from the archive
#Inputs: <collection-path> 
#      : [response-message-filename]
#      : [response-header-filename]
function dm_get_collection {

    USAGE="dm_get_collection  <collection-path> [response-message-filename] [response-header-filename]"

    if [ "$#" -lt 1 ] 
    then
        echo "ERROR: using dm_get_collection" >&2
        echo "recieved $0 $@" 
        echo "$USAGE" >&2
        return
    fi
    ITEM_PATH="$1"

    RESPONSE_MSG=${2-get-item-response-message.json.tmp}
    RESPONSE_HEADER=${3-get-item-response-header.tmp}

    dm_get_item collection/$ITEM_PATH  "$RESPONSE_MSG" "$RESPONSE_HEADER"

    RESPONSE_CODE=$(get_http_code $RESPONSE_HEADER)
    if [ "$RESPONSE_CODE" -ne 200 ]
    then
      echo "ERROR getting \"$ITEM_PATH\" " >&2
      echo "ERROR_CODE:\"$RESPONSE_CODE\"" >&2
      print_error_message "$RESPONSE_MSG" "$REPONSE_CODE"
      return
    else 
     
      #Check if the user needs the response header file 
      if [ -z "$3" ]
      then 
        rm "$RESPONSE_HEADER" 2> /dev/null
      fi

      if [ -z "$2" ]
      then
        print_json_message "$RESPONSE_MSG"    
        rm $RESPONSE_MSG 2> /dev/null 
      fi
    fi
}



#Download a dataObject synchronously 
#Inputs: logic-path 
#        destination-file
function dm_download_dataobject_sync {


    USAGE="USAGE:dm_download_dataobject_sync <logic-path> <destination-file>"

    if [ "$#" -lt 2 ] 
    then
        echo "ERROR: using dm_downlaod_dataobject_sync" >&2
        echo "recieved $@" 
        echo "$USAGE" >&2
        return 1
    fi

    RESPONSE_HEADER=download-dataobject-response-header.tmp

   
    OBJECT_PATH="$1"
    DESTINATION_PATH="$2"

    if [ -d "$DESTINATION_PATH"  ]
    then
      
        #Download the file with the same file name 
        FILE_NAME=$(basename "$OBJECT_PATH")
        if [ "$?" -ne 0 ]
        then
          echo "ERROR:Can not retrieve the file name from \"$OBJECT_PATH\"" >&2
          return 1
        fi

        DESTINATION_PATH=$DESTINATION_PATH/${FILE_NAME}
    fi


    SERVER=$(get_server)
    
    CONFIG="--config $HPC_DM_UTILS/curl-conf"

    TEMPLATE="$HPC_DM_UTILS/templates/download-sync-template.json"

    curl -H "Content-Type: application/json" -d @$TEMPLATE -X POST ${SERVER}/dataObject/$OBJECT_PATH/download  $CONFIG -H "Accept: application/json" -D $RESPONSE_HEADER -o $DESTINATION_PATH -s 2> curl-status 
    check_connection $RESPONSE_HEADER


    CODE=$(get_http_code "$RESPONSE_HEADER") 

    if [ "$CODE" -ne 200 ]
    then 
      #In this case the destination path file will contain the error code
      print_error_message "$DESTINATION_PATH" "$CODE" 
    else
      rm $RESPONSE_HEADER 2> /dev/null
    fi
}




