#!/bin/bash

if [ -z "$HPC_DM_UTILS" ]
then
    echo "ERROR, the HPC_DM_UTILS environment variable is not defined" 
    return 1
fi

#Add the utilities to the PATH
export PATH=$HPC_DM_UTILS/scripts/:$PATH

#If it is a windows environment, change the line ending of the scripts:
case "$(uname -s)" in
    
       CYGWIN*|MINGW32*|MSYS*)
        sed -i "s/\r$//" $HPC_DM_UTILS/hpcdme.properties-sample
        sed -i "s/\r$//" $HPC_DM_UTILS/scripts/*
        ;;
    
       # Add here more strings to compare
       # See correspondence table at the bottom of this answer
esac
