#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Check if the collection and the dataObject registration functions called in makeme were successful.

RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

query_by_metadata collection input.json 

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

get_json_value response-message.json message >&2

