#!/usr/bin/env bash
# maketest
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

#Register a project and a dataObject to be downloaded


#Clean previous results
./cleanme


#Register a collection, a folder, then a dataObject
source $HPC_DM_TEST/utils/functions
../../utils/maketest

#Register the download project
PROJECT_PATH="$(get_basefolder)/project-download"
register_collection_from_template "$PROJECT_PATH"
verify_registration $RESPONSE_HEADER

#Register a folder collection
NAME=`date +"%b-%d-%G-%H-%M-%S"`
FOLDER_PATH=$PROJECT_PATH/collection-${NAME}
echo $FOLDER_PATH > registered-folder-path.tmp
curl_register $HPC_DM_TEST/utils/templates/register-folder-template.json "$FOLDER_PATH" collection
verify_registration $RESPONSE_HEADER

#Register a dataObject inside the folder colleciton
DATAOBJECT_PATH=${FOLDER_PATH}/object-${NAME}.txt
echo $DATAOBJECT_PATH > registered-dataobject-path.tmp

NEW_TEMPLATE="register-dataobject.json.tmp"
update_uid $HPC_DM_TEST/utils/templates/register-dataobject-template.json "$NEW_TEMPLATE" 
curl_register register-dataobject.json.tmp  "$DATAOBJECT_PATH" dataObject 
verify_registration $RESPONSE_HEADER
