#!/usr/bin/env bash
# makeme
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to register a user before running the test 
# Usage: makeme [no arguments]

#Clean previous results
./cleanme

../utils/maketest
