#!/usr/bin/env bash
# makeme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


#import common functions
source ../utils/functions

#Run common script
$HPC_DM_TEST/utils/runtest

update_user

RESPONSE_CODE=`get_http_code $RESPONSE_HEADER`
echo $RESPONSE_CODE 


#Verify the user is updated
USER_ID=$(cat new-user-id.tmp)
RESPONSE_HEADER=get-user-response-header.tmp
RESPONSE_MSG=get-user-response-message.tmp

get_user $USER_ID $RESPONSE_HEADER $RESPONSE_MSG

get_http_code $RESPONSE_HEADER

EXIST_FIRST=$(grep "newtestfirst" $RESPONSE_MSG)
EXIST_LAST=$(grep "newtestlast" $RESPONSE_MSG)

if [ -z "$EXIST_FIRST" ] || [ -z "$EXIST_LAST" ]
then
    echo "ERROR: Updated name is not: newtestfirst newtestlast" >&2
fi

