#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.

# Common script to create tests by addin a user
# Usage: maketest [no arguments]

source $HPC_DM_TEST/utils/functions

#Clean previous results
./cleanme

#Call common maketest
$HPC_DM_TEST/utils/maketest

#Create a new user id 
#Make sure the new user has a new ID

register_user_from_template
