#!/usr/bin/env bash
# maketest 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.

# Common script to create tests by addin a user
# Usage: maketest [no arguments]

source $HPC_DM_TEST/utils/functions

#Clean previous results
./cleanme

#Call common maketest
$HPC_DM_TEST/utils/maketest

#Create a new user id 
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
NEW_ID="testid-$SUFFIX"
UPDATED_FIRST=`cat ../utils/register.json | sed "s/testfirst/testfirst-$SUFFIX/"`
UPDATED_LAST=`echo "$UPDATED_FIRST" | sed "s/testlast/testlast-$SUFFIX/"`
UPDATED_REGISTRATION=`echo "$UPDATED_LAST" | sed "s/testid/$NEW_ID/"`
echo "$UPDATED_REGISTRATION" > register.json.tmp
echo "$NEW_ID" > newid.tmp


#Register the new user
RESPONSE_HEADER=registration-response-header.tmp
RESPONSE_MSG=registration-response-message.json.tmp
SERVER=`cat $HPC_DM_TEST/utils/server`

curl -H "Content-Type: application/json" -d @register.json.tmp -X PUT ${SERVER}/hpc-server/user  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
check_connection $RESPONSE_HEADER

