#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-search/utils/search-functions


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json

search_by_metadata collection input.json dice_user

HTTP_CODE=`get_http_code $RESPONSE_HEADER`

ATTRIBUTE="name"
VALUE="dice test project 2"

#Make sure if there is a responce that the required project is not part of the results
if [ "$HTTP_CODE" -eq "200" ]
then
    #Make sure the response does not include the project named "$VALUE".
    RESPONSE_GROUPS=`cat $RESPONSE_MSG | tr "{" "\n"`
    PROJECT_GROUPS=`echo "$RESPONSE_GROUPS" | grep "$ATTRIBUTE"`
    PROJECT_NAMES=`get_json_value "$PROJECT_GROUPS" value`
    
    PROJECT_FOUND="FALSE"
    for project in "$PROJECT_NAMES"; do
        if [[ $project == *"$VALUE"*  ]]
        then
            PROJECT_FOUND="TRUE"
            break
        fi
    done 
    
    if [ "$PROJECT_FOUND" == "TRUE" ] 
    then
        echo "ERROR: PROJECT \"$VALUE\" IS PART OF THE RESULTS."  1>&2
    fi
fi
