#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions


source $HPC_DM_TEST/utils/functions

NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
NEW_FOLDER_PATH=$(get_basefolder)/project-${NAME}

curl_register input-template.json $NEW_FOLDER_PATH/object-${NAME}.txt dataObject

get_http_code $RESPONSE_HEADER >&2
get_json_value $RESPONSE_MSG  errorType >&2
EXPECTED_MSG="Invalid collection hierarchy"
get_json_value $RESPONSE_MSG message | sed "s#^$EXPECTED_MSG.*#$EXPECTED_MSG#" >&2
