#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]


#Clean previous files 
../../utils/cleantest

../../../utils/maketest
#Create policies file
#../../utils/maketest dataObjectMetadataValidationRules
#Register a project to add dataObjects to it

source $HPC_DM_TEST/utils/functions
USERID=`get_username $HPC_DM_TEST/utils/config`
RESPONSE_HEADER=update-no-hier-response-header.tmp
RESPONSE_MSG=update-no-hier-response-message.json.tmp
update_existing_user $USERID update-no-hierarchy.json  $RESPONSE_HEADER $RESPONSE_MSG

