#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]
#import common functions


source $HPC_DM_TEST/utils/functions
../utils/runtest


#Check if DOC update went through:
RESPONSE_HEADER=update-no-hier-response-header.tmp
verify_registration $RESPONSE_HEADER

sleep 1
NAME=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
NEW_FOLDER_PATH=/TEST_NO_HIER_Archive/auto-collection/folder-${NAME}
curl_register input.json $NEW_FOLDER_PATH/object-${NAME}.txt dataObject
get_http_code $RESPONSE_HEADER

#Reassign the DOC to DUMMY 
RESPONSE_HEADER=update-dummy-response-header.tmp
RESPONSE_MSG=update-dummy-response-message.json.tmp
update_existing_user $USERID update-dummy.json  $RESPONSE_HEADER $RESPONSE_MSG
verify_registration $RESPONSE_HEADER
