#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


sleep 1
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
QUERY_ID=queryid-$SUFFIX

register_query $QUERY_ID input.json

RESPONSE_HEADER=register-query-response-header.tmp
RESPONSE_MSG=register-query-response-message.json.tmp


HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

get_json_value $RESPONSE_MSG errorType  >&2
get_json_value $RESPONSE_MSG message | sed "s/Invalid named compound metadata query: Null compound query operator.*/Invalid named compound metadata query: Null compound query operator/" >&2
#Parse the response header. 


