#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


function register_project {

    source ../../../utils/functions
    USERID=`get_username ../../../utils/config`
    PROJECT_DESCRIPTION=$1
    DESTINATION_PATH="/${USERID}/dice-unit-test/project-search"
    echo "$DESTINATION_PATH" >> registered-project-name
    SERVER=`cat ../../../utils/server`
    RESPONSE_MSG=registration-response-message.json
    RESPONSE_HEADER=registration-response-header
    
    curl -H "Content-Type: application/json" -d @$PROJECT_DESCRIPTION -X PUT ${SERVER}/hpc-server/collection/${DESTINATION_PATH}  --config ../../../utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
    check_connection $RESPONSE_HEADER
}
function check_registration {
    #Check that the project was registered correctly
    REG_HTTP_CODE=`get_http_code registration-response-header`
    if [ "$REG_HTTP_CODE" != "201" ]  && [ "$REG_HTTP_CODE" != "200" ]
    then
        echo "FAILED TO REGISTER PROJECT BEFORE SEARCH. HTTP_CODE = $REG_HTTP_CODE" 1>&2
        exit
    fi
}

