#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest


verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp


FOLDER_PATH=collection/$(cat registered-folder-path.tmp)
OBJECT_GET_PATH=dataObject/$(cat registered-dataobject-path.tmp)

object_path=$(cat registered-dataobject-path.tmp)


RESPONSE_HEADER=get-item-response-header.tmp 
RESPONSE_MSG=get-item-response-message.json.tmp
get_item "$OBJECT_GET_PATH"  "$RESPONSE_HEADER" "$RESPONSE_MSG"

RESPONSE_HEADER=download-response-header.tmp 
RESPONSE_MSG=download-response-message.json.tmp
download_dataobject_sync $object_path 

code=$(get_http_code $RESPONSE_HEADER)
echo "Sync download request code:$code" >&2
get_json_value $RESPONSE_MSG errorType >&2
get_json_value $RESPONSE_MSG requestRejectReason >&2

