--
-- hpc_data_object_last_access_mv.sql
--
-- Distributed under the OSI-approved BSD 3-Clause License.
-- See http://ncip.github.com/HPC/LICENSE.txt for details.
--

BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -12003 THEN
      RAISE;
    END IF;
END;
/

CREATE MATERIALIZED VIEW IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV
REFRESH COMPLETE ON DEMAND
AS
WITH LAST_ACCESS_SOURCE AS (
  SELECT
    RESULT.PATH AS PATH,
    RESULT.COMPLETED AS LAST_ACCESSED_DATE,
    RESULT.USER_ID AS LAST_DOWNLOADED_BY,
    RESULT.DOC AS DOC,
    RESULT.ARCHIVE_LOCATION_FILE_CONTAINER_ID AS BUCKET,
    RESULT.DATA_SIZE AS DATA_SIZE,
    (
      SELECT MAX(CFG.BASE_PATH) KEEP (DENSE_RANK LAST ORDER BY LENGTH(CFG.BASE_PATH))
      FROM HPC_DATA_MANAGEMENT_CONFIGURATION CFG
      WHERE CFG.DOC = RESULT.DOC
        AND RESULT.PATH LIKE CFG.BASE_PATH || '%'
    ) AS BASE_PATH
  FROM HPC_DOWNLOAD_TASK_RESULT RESULT
  WHERE RESULT.PATH IS NOT NULL
    AND RESULT.COMPLETED IS NOT NULL
    AND (RESULT.RESULT = 'COMPLETED' OR RESULT.RESULT = 'SUCCESS')
)
SELECT
  PATH,
  MAX(LAST_ACCESSED_DATE) AS LAST_ACCESSED_DATE,
  MAX(LAST_DOWNLOADED_BY) KEEP (DENSE_RANK LAST ORDER BY LAST_ACCESSED_DATE) AS LAST_DOWNLOADED_BY,
  COUNT(*) AS DOWNLOAD_COUNT,
  MAX(DOC) KEEP (DENSE_RANK LAST ORDER BY LAST_ACCESSED_DATE) AS DOC,
  MAX(BASE_PATH) KEEP (DENSE_RANK LAST ORDER BY LAST_ACCESSED_DATE) AS BASE_PATH,
  MAX(BUCKET) KEEP (DENSE_RANK LAST ORDER BY LAST_ACCESSED_DATE) AS BUCKET,
  MAX(DATA_SIZE) KEEP (DENSE_RANK LAST ORDER BY LAST_ACCESSED_DATE) AS DATA_SIZE
FROM LAST_ACCESS_SOURCE
GROUP BY PATH;

CREATE UNIQUE INDEX HPC_DATA_OBJECT_LAST_ACCESS_MV_PATH_UQ
  ON IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV (PATH);

CREATE INDEX HPC_DATA_OBJECT_LAST_ACCESS_MV_DATE_IDX
  ON IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV (LAST_ACCESSED_DATE);

CREATE INDEX HPC_DATA_OBJECT_LAST_ACCESS_MV_DOC_IDX
  ON IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV (DOC);

CREATE INDEX HPC_DATA_OBJECT_LAST_ACCESS_MV_BASE_PATH_IDX
  ON IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV (BASE_PATH);

CREATE INDEX HPC_DATA_OBJECT_LAST_ACCESS_MV_BUCKET_IDX
  ON IRODS.HPC_DATA_OBJECT_LAST_ACCESS_MV (BUCKET);
