#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions


RESPONSE_HEADER=update-query-response-header.tmp
RESPONSE_MSG=update-query-response-message.json.tmp

register_query dxtest-nonexistent-query $HPC_DM_TEST/utils/templates/query-template.json POST

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

get_json_value $RESPONSE_MSG  errorType >&2
get_json_value $RESPONSE_MSG  message | sed "s/Query name doesn't exist.*/Query name doesn't exist/"  >&2

