#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
../utils/runtest

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

PROJECT_PATH=`cat registered-project-path.tmp`
DATAOBJECT_PATH="${PROJECT_PATH}"

#Register the dataObject 
curl_register input.json  "$DATAOBJECT_PATH" dataObject 

#Check the returned 
REG_HTTP_CODE=`get_http_code dataObject-registration-response-header.tmp`

RESPONSE_MSG=dataObject-registration-response-message.json.tmp 



ERROR_TYPE=$(get_json_value "$RESPONSE_MSG" errorType)

EXPECTED_MSG="Path already exists as a directory"
ERROR_MSG=$(get_json_value "$RESPONSE_MSG" message)
CLEANED_MSG=$(echo $ERROR_MSG | sed "s#$EXPECTED_MSG.*#$EXPECTED_MSG#")


echo $REG_HTTP_CODE 1>&2  
echo $ERROR_TYPE 1>&2
echo $CLEANED_MSG 1>&2






