#!/usr/bin/env bash
# makeme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

response_hdr=group-registration-response-header.tmp
verify_registration $response_hdr

#Search by groupID 
group_id=$(cat new-group-id.tmp)
response_hdr=search-groups-response-header.tmp
response_msg=search-groups-response-message.json.tmp

search_groups
get_http_code $response_hdr

#Make sure the group exists
group_exists=$(grep "$group_id" $response_msg)
if [ -z "$group_exists" ]
then
    echo "ERROR: Can not find $group_id in $response_msg" >&2
fi
