#!/usr/bin/env bash
# makeme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

response_hdr=user-registration-response-header.tmp
verify_registration $response_hdr

#Search by userID
user_id=$(cat new-user-id.tmp)
response_hdr=search-active-users-response-header.tmp
response_msg=search-active-users-response-message.json.tmp

search_users 
get_http_code $response_hdr

#compare first name, last name
user_exists=$(grep "$user_id" $response_msg)
if [ -z "$user_exists" ]
then
    echo "ERROR: Can not find $user_id in $response_msg" >&2
fi
