#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions
source $HPC_DM_TEST/test-permission/utils/functions

#Run the common runtest
$HPC_DM_TEST/test-permission/utils/runtest


RESPONSE_HEADER=get-permission-response-header.tmp
RESPONSE_MSG=get-permission-response-message.json.tmp
get_permission collection/$(get_basefolder)/dice_project2

PERMISSION_LINE=$(cat $RESPONSE_MSG | tr "{" "\n" | grep \"dice_user\")
get_json_value "$PERMISSION_LINE" permission 
