#!/usr/bin/env bash
# makeme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#

# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

#Search by groupID 
response_hdr=search-groups-response-header.tmp
response_msg=search-groups-response-message.json.tmp

search_groups %weird-pattern%
get_http_code $response_hdr
