#!/usr/bin/env bash
# makeme
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#


# Script to make this test
# Usage: makeme [no arguments]


#import common functions
source $HPC_DM_TEST/utils/functions

./cleanme

#Clean previous parsed policies file
../../utils/cleantest

#Common maketest 
$HPC_DM_TEST/utils/maketest

#Register a collection
../utils/maketest

#Register a dataObject

#Update the userid
update_uid input-template.json input.json

#Check if collection registration went through:
verify_registration collection-registration-response-header.tmp

#Register a new dataObject
SUFFIX=`date +"%b-%d-%G-%H-%M-%S"`
USERID=`get_username $HPC_DM_TEST/utils/config`
PROJECT_PATH=`cat registered-project-path.tmp`
DATAOBJECT_PATH="${PROJECT_PATH}/object-${SUFFIX}.txt"

echo "$DATAOBJECT_PATH" > registered-dataobject-path.tmp

#Register the dataOjbect 
curl_register input.json  "$DATAOBJECT_PATH" dataObject 




