#!/usr/bin/env bash
# Readme.txt
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source ../../utils/functions

../utils/runtest

verify_registration  collection-registration-response-header.tmp
verify_registration  dataObject-registration-response-header.tmp

OBJECT_PATH=`cat registered-dataobject-path.tmp`


RESPONSE_HEADER=response-header
RESPONSE_MSG=response-message.json
download_async "dataObject/$OBJECT_PATH"  "input.json"

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
ERROR_TYPE=`get_json_value $RESPONSE_MSG errorType`
ERROR_MSG=`get_json_value $RESPONSE_MSG message`

echo $HTTP_CODE 1>&2 
echo $ERROR_TYPE 1>&2

MSG_PREFIX="[GLOBUS] Endpoint doesn't exist or is inactive. Make sure the endpoint UUID is correct and active"

if [[ "$ERROR_MSG" == *"$MSG_PREFIX"* ]]
then
    echo $MSG_PREFIX  1>&2
fi
