#!/usr/bin/env bash
# runme 
# @author: George Zaki 
# 
# Copyright Leidos Biomedical Research, Inc
# 
# Distributed under the OSI-approved BSD 3-Clause License.
# See http://ncip.github.com/HPC/LICENSE.txt for details.
#
# Script to run this test
# Usage: runme [no arguments]

#import common functions
source $HPC_DM_TEST/utils/functions

RESPONSE_MSG="delete-query-response-message.json.tmp"

delete_query "dxtestlkj;lkj;ljk;lkj;lkjl;j-nonexistent-query-id"

HTTP_CODE=`get_http_code $RESPONSE_HEADER`
echo $HTTP_CODE >&2

ERROR_MSG=$(get_json_value $RESPONSE_MSG message)

echo $ERROR_MSG >&2

