name: Build  DME HPC API workflow
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      environment:
        description: env to build war file
        type: choice
        default: build
        options:
          - build
      code_branch:
        description: branch to build
        required: true
        default: master
run-name: "Build for DME API (branch: ${{ github.event.inputs.code_branch }})"
jobs:
  build:
    name: Build war file
    runs-on:
      group: cbiit-global-runners
      #labels: [self-hosted]
      labels: [nonprod-org-runner]
      #labels: [prod-org-runner]
    environment: ${{ inputs.environment }}
    env:
      CODE_BRANCH: "${{ github.event.inputs.code_branch }}"
      SPRING_DS_PWD: ${{ secrets.SPRING_DS_PWD }}
    steps:
      - name: check git installation
        run: git --version

      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          #ref: ${{ github.event.inputs.code_branch }}
          ref: ${{ env.CODE_BRANCH }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - name: set up maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.4'
      #- name: install ojdbc6 to local maven repo
        #run: |
          #mvn install:install-file \
            #-Dfile=/path/to/ojdbc6.jar \
            #-DgroupId=com.oracle \
            #-DartifactId=ojdbc6 \
            #-Dversion=11.2.0.4 \
            #-Dpackaging=jar

      - name: build the war file
        run: |
          #cd HPC_DME_APIs/src
          cd $GITHUB_WORKSPACE
          #sed -i "s|^spring.datasource.password=.*|spring.datasource.password=${{ env.SPRING_DS_PWD }}|" src/main/resources/application.properties
          mvn clean install -Ddev
      - name: upload artifacts for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dme-dev-hpc-api-artifacts
          path: |
            src/hpc-server/hpc-ws-rs-impl/target/*.war
            src/hpc-server/hpc-scheduler/target/*.war
            src/hpc-server/hpc-scheduler-migration/target/*.war
